### ISSUE TITLE
consider using args instead of input files

### ISSUE THREAD

**Issue by thiagomanel** [simsab-ufcg/Promethee2#36]
For example, we can use something like -criterion name path/to/data function_name arg0 arg1 -criterion name path/to/data function_name arg0 arg1 -criterion name path/to/data function_name arg0 arg1 -o /path/to/output

Note that, we can made available python/bash script to translate our current file based configuration files to this args style

**Comment by gabrielfelipeg** [comment]
Our current Umbu, Opt and Fast implementation using args instead of input files, only Vanilla still is using input files.
